In [3]:
import pandas as pd
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")
print(df)

            country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100   2024-05-16 9:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100   2024-05-16 9:45                 26.0
...                    ...               ...                  ...
135068          1775975400   2026-04-12 2:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400   2026-04-12 9:30                 19.3
135071          1775975400   2026-04-12 8:30                 18.5
135072          1775975400   2026-04-12 8:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise   sunset  moonrise   moonset       moon_phase  \
0       4:50 AM  6:50 PM  12:12 PM   1:11 AM   Waxing Gibbous
1       5:21 AM  7:54 PM  12:58 PM   2:14 AM   Waxing Gibbous
2       5:40 AM  7:50 PM   1:15 PM   2:14 AM   Waxing Gibbous
3       6:31 AM  9:11 PM   2:12 PM   3:31 AM   Waxing Gibbous
4       6:12 AM  5:55 PM   1:17 PM  12:38 AM   Waxing Gibbous
...         ...      ...       ...       ...              ...
135068  6:18 AM  6:38 PM   2:36 AM   2:31 PM  Waning Crescent
135069  5:41 AM  6:14 PM   2:02 AM   1:21 PM  Waning Crescent
135070  5:51 AM  6:17 PM   2:06 AM   1:45 PM  Waning Crescent
135071  6:14 AM  6:01 PM   1:26 AM   2:30 PM  Waning Crescent
135072  6:04 AM  5:49 PM   1:10 AM   2:22 PM  Waning Crescent

        moon_illumination
0                      55
1                      55
2                      55
3                      55
4                      55
...                   ...
135068                 31
135069                 35
135070                 34
135071                 33
135072                 33

[135073 rows x 41 columns]

#head

first five rows

In [4]:
df.head

<bound method NDFrame.head of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100   2024-05-16 9:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100   2024-05-16 9:45                 26.0
...                    ...               ...                  ...
135068          1775975400   2026-04-12 2:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400   2026-04-12 9:30                 19.3
135071          1775975400   2026-04-12 8:30                 18.5
135072          1775975400   2026-04-12 8:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise   sunset  moonrise   moonset       moon_phase  \
0       4:50 AM  6:50 PM  12:12 PM   1:11 AM   Waxing Gibbous
1       5:21 AM  7:54 PM  12:58 PM   2:14 AM   Waxing Gibbous
2       5:40 AM  7:50 PM   1:15 PM   2:14 AM   Waxing Gibbous
3       6:31 AM  9:11 PM   2:12 PM   3:31 AM   Waxing Gibbous
4       6:12 AM  5:55 PM   1:17 PM  12:38 AM   Waxing Gibbous
...         ...      ...       ...       ...              ...
135068  6:18 AM  6:38 PM   2:36 AM   2:31 PM  Waning Crescent
135069  5:41 AM  6:14 PM   2:02 AM   1:21 PM  Waning Crescent
135070  5:51 AM  6:17 PM   2:06 AM   1:45 PM  Waning Crescent
135071  6:14 AM  6:01 PM   1:26 AM   2:30 PM  Waning Crescent
135072  6:04 AM  5:49 PM   1:10 AM   2:22 PM  Waning Crescent

        moon_illumination
0                      55
1                      55
2                      55
3                      55
4                      55
...                   ...
135068                 31
135069                 35
135070                 34
135071                 33
135072                 33

[135073 rows x 41 columns]>

#tail

last five rows

In [5]:
df.tail

<bound method NDFrame.tail of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100   2024-05-16 9:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100   2024-05-16 9:45                 26.0
...                    ...               ...                  ...
135068          1775975400   2026-04-12 2:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400   2026-04-12 9:30                 19.3
135071          1775975400   2026-04-12 8:30                 18.5
135072          1775975400   2026-04-12 8:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise   sunset  moonrise   moonset       moon_phase  \
0       4:50 AM  6:50 PM  12:12 PM   1:11 AM   Waxing Gibbous
1       5:21 AM  7:54 PM  12:58 PM   2:14 AM   Waxing Gibbous
2       5:40 AM  7:50 PM   1:15 PM   2:14 AM   Waxing Gibbous
3       6:31 AM  9:11 PM   2:12 PM   3:31 AM   Waxing Gibbous
4       6:12 AM  5:55 PM   1:17 PM  12:38 AM   Waxing Gibbous
...         ...      ...       ...       ...              ...
135068  6:18 AM  6:38 PM   2:36 AM   2:31 PM  Waning Crescent
135069  5:41 AM  6:14 PM   2:02 AM   1:21 PM  Waning Crescent
135070  5:51 AM  6:17 PM   2:06 AM   1:45 PM  Waning Crescent
135071  6:14 AM  6:01 PM   1:26 AM   2:30 PM  Waning Crescent
135072  6:04 AM  5:49 PM   1:10 AM   2:22 PM  Waning Crescent

        moon_illumination
0                      55
1                      55
2                      55
3                      55
4                      55
...                   ...
135068                 31
135069                 35
135070                 34
135071                 33
135072                 33

[135073 rows x 41 columns]>

#sample

selecting seven rows

In [6]:
df.sample(7)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
94611,Luxembourg,Luxembourg,49.6117,6.1300,Europe/Luxembourg,1757924100,2025-09-15 10:15,16.3,61.3,Light rain shower,...,4.625,5.55,1,1,7:12 AM,7:49 PM,No moonrise,5:09 PM,Waning Crescent,45
20064,Malta,Valletta,35.9000,14.5100,Europe/Malta,1724848200,2024-08-28 14:30,31.0,87.8,Thundery outbreaks possible,...,15.800,19.20,2,2,6:31 AM,7:35 PM,12:39 AM,4:18 PM,Waning Crescent,33
24130,Indonesia,Jakarta,-6.2100,106.8500,Asia/Jakarta,1726656300,2024-09-18 17:45,29.2,84.6,Partly cloudy,...,88.800,128.39,4,10,5:44 AM,5:49 PM,6:06 PM,5:41 AM,Full Moon,100
122633,Ethiopia,Addis Ababa,9.0333,38.7000,Africa/Addis_Ababa,1770446700,2026-02-07 9:45,17.2,62.9,Patchy rain nearby,...,32.350,42.55,2,3,6:46 AM,6:33 PM,11:12 PM,10:30 AM,Waning Gibbous,75
120715,Kenya,Nairobi,-1.2833,36.8167,Africa/Nairobi,1769583600,2026-01-28 10:00,21.2,70.2,Partly cloudy,...,17.750,19.65,2,2,6:40 AM,6:51 PM,2:29 PM,1:52 AM,Waxing Gibbous,69
97535,Madagascar,Antananarivo,-18.9167,47.5167,Indian/Antananarivo,1759219200,2025-09-30 11:00,28.1,82.6,Sunny,...,7.450,7.75,1,1,5:33 AM,5:48 PM,11:24 AM,12:22 AM,First Quarter,49
118488,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1768461300,2026-01-15 14:15,22.1,71.8,Partly cloudy,...,85.850,86.95,4,10,6:36 AM,5:36 PM,3:37 AM,2:26 PM,Waning Crescent,15

#shape

tatal number of rows and columns

In [7]:
df.shape

(135073, 41)

#columns

all columns of this data

In [8]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

#info

information about entire data

In [9]:
df.info

<bound method DataFrame.info of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100   2024-05-16 9:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100   2024-05-16 9:45                 26.0
...                    ...               ...                  ...
135068          1775975400   2026-04-12 2:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400   2026-04-12 9:30                 19.3
135071          1775975400   2026-04-12 8:30                 18.5
135072          1775975400   2026-04-12 8:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise   sunset  moonrise   moonset       moon_phase  \
0       4:50 AM  6:50 PM  12:12 PM   1:11 AM   Waxing Gibbous
1       5:21 AM  7:54 PM  12:58 PM   2:14 AM   Waxing Gibbous
2       5:40 AM  7:50 PM   1:15 PM   2:14 AM   Waxing Gibbous
3       6:31 AM  9:11 PM   2:12 PM   3:31 AM   Waxing Gibbous
4       6:12 AM  5:55 PM   1:17 PM  12:38 AM   Waxing Gibbous
...         ...      ...       ...       ...              ...
135068  6:18 AM  6:38 PM   2:36 AM   2:31 PM  Waning Crescent
135069  5:41 AM  6:14 PM   2:02 AM   1:21 PM  Waning Crescent
135070  5:51 AM  6:17 PM   2:06 AM   1:45 PM  Waning Crescent
135071  6:14 AM  6:01 PM   1:26 AM   2:30 PM  Waning Crescent
135072  6:04 AM  5:49 PM   1:10 AM   2:22 PM  Waning Crescent

        moon_illumination
0                      55
1                      55
2                      55
3                      55
4                      55
...                   ...
135068                 31
135069                 35
135070                 34
135071                 33
135072                 33

[135073 rows x 41 columns]>

#dtypes

default data type

In [10]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

#iloc

the value of first rows and columns

In [13]:
df.iloc[1]

country                                  Albania
location_name                             Tirana
latitude                                   41.33
longitude                                  19.82
timezone                           Europe/Tirane
last_updated_epoch                    1715849100
last_updated                    2024-05-16 10:45
temperature_celsius                         19.0
temperature_fahrenheit                      66.2
condition_text                     Partly cloudy
wind_mph                                     6.9
wind_kph                                    11.2
wind_degree                                  320
wind_direction                                NW
pressure_mb                                 1012
pressure_in                                29.88
precip_mm                                    0.1
precip_in                                    0.0
humidity                                      94
cloud                                         75
feels_like_celsius                          19.0
feels_like_fahrenheit                       66.2
visibility_km                               10.0
visibility_miles                               6
uv_index                                     5.0
gust_mph                                    11.4
gust_kph                                    18.4
air_quality_Carbon_Monoxide                193.6
air_quality_Ozone                           97.3
air_quality_Nitrogen_dioxide                 0.9
air_quality_Sulphur_dioxide                  0.1
air_quality_PM2.5                            1.1
air_quality_PM10                             2.0
air_quality_us-epa-index                       1
air_quality_gb-defra-index                     1
sunrise                                  5:21 AM
sunset                                   7:54 PM
moonrise                                12:58 PM
moonset                                  2:14 AM
moon_phase                        Waxing Gibbous
moon_illumination                             55
Name: 1, dtype: object

In [14]:
len(df[df["moon_illumination"]>10])

107444

In [15]:
df["timezone"].str.split("/")

0              [Asia, Kabul]
1           [Europe, Tirane]
2          [Africa, Algiers]
3          [Europe, Andorra]
4           [Africa, Luanda]
                 ...
135068    [America, Caracas]
135069       [Asia, Bangkok]
135070          [Asia, Aden]
135071      [Africa, Lusaka]
135072      [Africa, Harare]
Name: timezone, Length: 135073, dtype: object

In [16]:
df["moon_illumination"].mean()

np.float64(49.98644436712)

In [17]:
df["moon_illumination"].max()

100

In [18]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.sort_values(by="temperature_celsius")

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
118990,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768719600,2026-01-18 15:00,-29.8,-21.6,Mist,...,9.15,9.350,1,1,8:35 AM,5:31 PM,8:39 AM,4:36 PM,Waning Crescent,1
119182,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768893300,2026-01-20 15:15,-28.9,-20.0,Sunny,...,59.45,60.650,3,8,8:33 AM,5:34 PM,9:33 AM,7:04 PM,Waxing Crescent,1
121617,Belarus,Minsk,53.9000,27.5667,Europe/Minsk,1770015600,2026-02-02 10:00,-26.9,-16.4,Freezing fog,...,10.35,14.950,1,1,8:55 AM,5:53 PM,6:36 PM,9:24 AM,Waning Gibbous,100
118606,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768547700,2026-01-16 15:15,-26.8,-16.2,Mist,...,14.25,14.950,1,2,8:36 AM,5:28 PM,7:09 AM,2:30 PM,Waning Crescent,9
118801,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768633200,2026-01-17 15:00,-25.9,-14.6,Partly cloudy,...,17.05,17.350,2,2,8:36 AM,5:30 PM,7:59 AM,3:29 PM,Waning Crescent,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85049,Kuwait,Kuwait City,29.3667,47.9600,Asia/Kuwait,1753691400,2025-07-28 11:30,48.8,119.8,Sunny,...,100.64,503.015,4,10,5:06 AM,6:43 PM,8:26 AM,9:03 PM,Waxing Crescent,11
8425,Kuwait,Kuwait City,29.3700,47.9600,Asia/Kuwait,1719494100,2024-06-27 16:15,48.9,120.0,Sunny,...,29.00,133.500,2,3,4:51 AM,6:52 PM,11:08 PM,10:13 AM,Waning Gibbous,71
11145,Iraq,Baghdad,33.3400,44.3900,Asia/Baghdad,1720701900,2024-07-11 15:45,49.1,120.3,Sunny,...,12.30,39.500,1,2,5:02 AM,7:14 PM,9:58 AM,10:37 PM,Waxing Crescent,23
7460,Iraq,Baghdad,33.3400,44.3900,Asia/Baghdad,1719063900,2024-06-22 16:45,49.1,120.4,Partly cloudy,...,16.10,47.900,2,2,4:54 AM,7:16 PM,8:06 PM,4:42 AM,Full Moon,100
6896,Kuwait,Kuwait City,29.3700,47.9600,Asia/Kuwait,1718804700,2024-06-19 16:45,49.2,120.6,Sunny,...,33.60,187.000,2,3,4:49 AM,6:50 PM,4:33 PM,2:17 AM,Waxing Gibbous,90

In [21]:
df["timezone"]=df["timezone"].str.replace("+","")

In [22]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 9:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 9:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 2:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 9:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 8:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 8:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33

In [23]:
df['continent']=df["timezone"].str.split('/').str[0]

In [24]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 9:45,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 9:45,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 2:30,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 9:30,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 8:30,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 8:30,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

In [25]:
df['last_updated']=pd.to_datetime(df['last_updated'])

In [26]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

In [27]:
df.columns=df.columns.str.strip().str.lower()

In [28]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

In [29]:
df['location_name']=df['location_name'].str.strip()

In [30]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

#head

first five rows of this data

In [31]:
print(df.head())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch        last_updated  temperature_celsius  \
0          1715849100 2024-05-16 13:15:00                 26.6
1          1715849100 2024-05-16 10:45:00                 19.0
2          1715849100 2024-05-16 09:45:00                 23.0
3          1715849100 2024-05-16 10:45:00                  6.3
4          1715849100 2024-05-16 09:45:00                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_pm10  \
0                    79.8  Partly Cloudy  ...              26.6
1                    66.2  Partly cloudy  ...               2.0
2                    73.4          Sunny  ...              18.4
3                    43.3  Light drizzle  ...               0.9
4                    78.8  Partly cloudy  ...             262.3

   air_quality_us-epa-index  air_quality_gb-defra-index  sunrise   sunset  \
0                         1                           1  4:50 AM  6:50 PM
1                         1                           1  5:21 AM  7:54 PM
2                         1                           1  5:40 AM  7:50 PM
3                         1                           1  6:31 AM  9:11 PM
4                         5                          10  6:12 AM  5:55 PM

   moonrise   moonset      moon_phase  moon_illumination  continent
0  12:12 PM   1:11 AM  Waxing Gibbous                 55       Asia
1  12:58 PM   2:14 AM  Waxing Gibbous                 55     Europe
2   1:15 PM   2:14 AM  Waxing Gibbous                 55     Africa
3   2:12 PM   3:31 AM  Waxing Gibbous                 55     Europe
4   1:17 PM  12:38 AM  Waxing Gibbous                 55     Africa

[5 rows x 42 columns]

In [32]:
df['latitude']=pd.to_numeric(df['latitude'],errors='coerce')

In [33]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

In [34]:
df['longitude']=pd.to_numeric(df['longitude'],errors='coerce')

In [35]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa

In [36]:
df.describe()

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,...,gust_kph,air_quality_carbon_monoxide,air_quality_ozone,air_quality_nitrogen_dioxide,air_quality_sulphur_dioxide,air_quality_pm2.5,air_quality_pm10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,135073.000000,135073.000000,1.350730e+05,135073,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,...,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000
mean,19.208948,21.961711,1.745908e+09,2025-04-29 08:31:05.284698112,21.283607,70.312259,8.021764,12.913410,168.894909,1014.069244,...,18.264350,461.415911,58.100332,15.007413,10.365922,24.211112,48.433111,1.699200,2.605791,49.986444
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.730970e+09,2024-11-07 05:00:00,16.000000,60.800000,3.800000,6.100000,80.000000,1010.000000,...,10.300000,203.500000,38.000000,1.665000,1.110000,7.050000,9.990000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.745916e+09,2025-04-29 10:45:00,24.000000,75.200000,6.700000,10.800000,161.000000,1014.000000,...,15.300000,294.150000,55.000000,5.550000,2.405000,14.200000,19.980000,1.000000,2.000000,50.000000
75%,40.400000,49.882200,1.760860e+09,2025-10-19 13:45:00,28.000000,82.400000,11.000000,17.600000,256.000000,1018.000000,...,24.200000,460.650000,74.000000,17.390000,8.325000,27.750000,41.450000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.775975e+09,2026-04-12 19:30:00,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000
std,24.416748,65.787645,1.734686e+07,NaN,9.699084,17.458216,7.225402,11.624983,103.706143,10.369057,...,13.829708,758.835655,30.777578,23.723174,35.691840,36.911798,149.473695,0.941003,2.445307,35.022525

In [48]:
df['time']=df['last_updated'].dt.time

In [49]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,data,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia,2024-05-16,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe,2024-05-16,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa,2024-05-16,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe,2024-05-16,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa,2024-05-16,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America,2026-04-12,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia,2026-04-12,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia,2026-04-12,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa,2026-04-12,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa,2026-04-12,2026-04-12,08:30:00

In [50]:
df['date']=df['last_updated'].dt.date

In [51]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,data,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia,2024-05-16,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe,2024-05-16,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa,2024-05-16,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe,2024-05-16,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa,2024-05-16,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America,2026-04-12,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia,2026-04-12,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia,2026-04-12,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa,2026-04-12,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa,2026-04-12,2026-04-12,08:30:00

In [52]:
df=df.drop(columns=['data'])

In [53]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa,2026-04-12,08:30:00

In [60]:
split_columns=df['timezone'].str.split('/',n=1,expand=True)

In [61]:
df['continent']=split_columns[0]

In [62]:
df['city']=split_columns[1]

In [63]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,date,time,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55,Asia,2024-05-16,13:15:00,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55,Europe,2024-05-16,10:45:00,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55,Africa,2024-05-16,09:45:00,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55,Europe,2024-05-16,10:45:00,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55,Africa,2024-05-16,09:45:00,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31,America,2026-04-12,02:30:00,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35,Asia,2026-04-12,13:30:00,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34,Asia,2026-04-12,09:30:00,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33,Africa,2026-04-12,08:30:00,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33,Africa,2026-04-12,08:30:00,Harare